from __future__ import annotations

import argparse
from pathlib import Path
import platform
from typing import Any


def _load_yaml(path: Path) -> dict[str, Any]:
    import yaml

    with path.open("r", encoding="utf-8") as stream:
        payload = yaml.safe_load(stream) or {}
    if not isinstance(payload, dict):
        raise ValueError(f"Expected a YAML object in {path}")
    return payload


def _write_yaml(path: Path, payload: dict[str, Any]) -> None:
    import yaml

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as stream:
        yaml.safe_dump(payload, stream, sort_keys=False)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _merge_settings(detected: dict[str, str], overrides_path: Path | None) -> dict[str, str]:
    settings = dict(detected)
    if not overrides_path or not overrides_path.exists():
        return settings

    payload = _load_yaml(overrides_path)
    override_values = payload.get("variables", payload)
    if not isinstance(override_values, dict):
        raise ValueError("Settings YAML must be a mapping or contain a top-level 'variables' mapping")

    for key, value in override_values.items():
        if isinstance(value, (str, int, float)):
            settings[str(key)] = str(value)
    return settings


def _expand_text(text: str, settings: dict[str, str]) -> str:
    expanded = text.replace(
        "@DATACRUMBS_PROJECT_PATH@/etc/datacrumbs", settings["DATACRUMBS_PROJECT_PATH"]
    )
    for key, value in settings.items():
        expanded = expanded.replace(f"@{key}@", value)
    return expanded


def _render_shell_settings(settings: dict[str, str]) -> str:
    lines = [
        "# Generated by datacrumbs-utils configure_templates.py",
    ]
    for key in sorted(settings):
        value = settings[key].replace('"', '\\"')
        lines.append(f'export {key}="{value}"')
        lines.append(f"readonly {key}")
    lines.append("")
    return "\n".join(lines)


def _render_header(settings: dict[str, str]) -> str:
    lines = [
        "#ifndef DATACRUMBS_UTILS_CONFIG_H",
        "#define DATACRUMBS_UTILS_CONFIG_H",
        "",
    ]
    for key in sorted(settings):
        value = settings[key].replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'#define {key} "{value}"')
    lines.extend(["", "#endif  // DATACRUMBS_UTILS_CONFIG_H", ""])
    return "\n".join(lines)


def _configure_configs(source_root: Path, output_config_dir: Path, settings: dict[str, str]) -> None:
    for template_path in sorted((source_root / "configs").glob("*.yaml")):
        expanded = _expand_text(template_path.read_text(encoding="utf-8"), settings)
        destination = output_config_dir / template_path.name
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(expanded, encoding="utf-8")


def _copy_runtime_assets(source_root: Path, output_data_dir: Path) -> None:
    for data_path in sorted((source_root / "data").glob("*.json")):
        destination = output_data_dir / data_path.name
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(data_path.read_text(encoding="utf-8"), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Expand datacrumbs-utils YAML templates")
    parser.add_argument("--source-root", required=True)
    parser.add_argument("--output-config-dir", required=True)
    parser.add_argument("--output-data-dir", required=True)
    parser.add_argument("--output-include-dir", required=True)
    parser.add_argument("--output-manifest", required=True)
    parser.add_argument("--settings")
    parser.add_argument("--kernel-uname-r", required=True)
    parser.add_argument("--kernel-headers-path", default="")
    parser.add_argument("--libc-so", required=True)
    args = parser.parse_args()

    source_root = Path(args.source_root).resolve()
    output_config_dir = Path(args.output_config_dir).resolve()
    output_data_dir = Path(args.output_data_dir).resolve()
    output_include_dir = Path(args.output_include_dir).resolve()
    output_manifest = Path(args.output_manifest).resolve()

    detected = {
        "DATACRUMBS_PROJECT_PATH": str(source_root),
        "DATACRUMBS_KERNEL_UNAME_R": args.kernel_uname_r,
        "DATACRUMBS_KERNEL_HEADERS_PATH": args.kernel_headers_path,
        "DATACRUMBS_LIBC_SO": args.libc_so,
        "DATACRUMBS_HOST_ARCH": platform.machine(),
    }
    settings = _merge_settings(detected, Path(args.settings) if args.settings else None)

    _configure_configs(source_root, output_config_dir, settings)
    _copy_runtime_assets(source_root, output_data_dir)
    _write_text(output_config_dir / "project.env.local", _render_shell_settings(settings))
    _write_text(output_include_dir / "datacrumbs_utils_config.h", _render_header(settings))

    manifest = {
        "variables": settings,
    }
    _write_yaml(output_manifest, manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())