capture_probes:
  - name: custom1
    start_event_id: 100000
    probe: custom
    type: custom
    file: @DATACRUMBS_PROJECT_PATH@/etc/datacrumbs/plugins/custom_probes/sys_io/sysio.bpf.c
    probes: @DATACRUMBS_PROJECT_PATH@/etc/datacrumbs/plugins/custom_probes/sys_io/probes.json
    process_header: @DATACRUMBS_PROJECT_PATH@/etc/datacrumbs/plugins/custom_probes/sys_io/sysio_process.h
    event_type: 2
  - name: libc
    probe: uprobe
    type: binary
    file: @DATACRUMBS_LIBC_SO@
    regex: .*fork.*
  - name: python
    probe: usdt
    type: usdt
    binary_path: /lib64/libpython3.6m.so.1.0
    provider: python
  - name: os_page_cache
    probe: kprobe
    type: header
    file: /usr/src/kernels/@DATACRUMBS_KERNEL_UNAME_R@/include/linux/pagemap.h
  - name: shm
    probe: kprobe
    type: header
    file: /usr/src/kernels/@DATACRUMBS_KERNEL_UNAME_R@/include/linux/shmem_fs.h
  - name: iomap
    probe: kprobe
    type: ksym
    regex: ^iomap(?!.*cold).*