capture_probes:
  - name: custom1
    start_event_id: 100000
    probe: custom
    type: custom
    file: @DATACRUMBS_PROJECT_PATH@/etc/datacrumbs/plugins/custom_probes/sys_io/sysio.bpf.c
    probes: @DATACRUMBS_PROJECT_PATH@/etc/datacrumbs/plugins/custom_probes/sys_io/probes.json
    process_header: @DATACRUMBS_PROJECT_PATH@/etc/datacrumbs/plugins/custom_probes/sys_io/sysio_process.h
    event_type: 2
  - name: sys
    probe: syscalls
    type: header
    file: /usr/src/kernels/@DATACRUMBS_KERNEL_UNAME_R@/include/linux/syscalls.h
    regex: sys_.*
  - name: os_page_cache
    probe: kprobe
    type: header
    file: /usr/src/kernels/@DATACRUMBS_KERNEL_UNAME_R@/include/linux/pagemap.h
  - name: lustre
    probe: kprobe
    type: binary
    file: /usr/lib/modules/5.14.0-570.55.1.1toss.t5.x86_64/weak-updates/lustre/fs/lustre.ko
    regex: (?!.*__)(?!.*:)(?!.*constprop)(?!.*isra).*
  - name: mdc
    probe: kprobe
    type: binary
    file: /usr/lib/modules/5.14.0-570.55.1.1toss.t5.x86_64/weak-updates/lustre/fs/mdc.ko
    regex: (?!.*__)(?!.*:)(?!.*constprop)(?!.*isra).*
  - name: mgc
    probe: kprobe
    type: binary
    file: /usr/lib/modules/5.14.0-570.55.1.1toss.t5.x86_64/weak-updates/lustre/fs/mgc.ko
    regex: (?!.*__)(?!.*:)(?!.*constprop)(?!.*isra).*
  - name: osc
    probe: kprobe
    type: binary
    file: /usr/lib/modules/5.14.0-570.55.1.1toss.t5.x86_64/weak-updates/lustre/fs/osc.ko
    regex: (?!.*__)(?!.*:)(?!.*constprop)(?!.*isra).*
  - name: ptlrpc
    probe: kprobe
    type: binary
    file: /usr/lib/modules/5.14.0-570.55.1.1toss.t5.x86_64/weak-updates/lustre/fs/ptlrpc.ko
    regex: (?!.*__)(?!.*:)(?!.*constprop)(?!.*isra).*
  - name: mpi
    probe: uprobe
    type: binary
    file: /opt/toss/openmpi/4.1/gnu/lib/libmpi.so
    regex: .*
  - name: ior
    probe: uprobe
    type: binary
    file: /home/haridev/software/ior/install/bin/ior
    regex: .*
  - name: iomap
    probe: kprobe
    type: ksym
    regex: ^iomap(?!.*cold).*
  - name: xfs
    probe: kprobe
    type: ksym
    regex: ^xfs(?!.*cold).*
  - name: libc
    probe: uprobe
    type: binary
    file: @DATACRUMBS_LIBC_SO@
    regex: .*