#include <sqlite3.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>

namespace {

std::string cmake_quote(const std::string& value) {
  return "[==[" + value + "]==]";
}

std::map<std::string, std::string> load_table(sqlite3* db, const char* table_name) {
  std::map<std::string, std::string> values;
  const std::string sql = std::string("SELECT key, value FROM ") + table_name + ";";
  sqlite3_stmt* statement = nullptr;
  if (sqlite3_prepare_v2(db, sql.c_str(), -1, &statement, nullptr) != SQLITE_OK) {
    throw std::runtime_error(std::string("failed to query table ") + table_name);
  }

  while (sqlite3_step(statement) == SQLITE_ROW) {
    const unsigned char* key = sqlite3_column_text(statement, 0);
    const unsigned char* value = sqlite3_column_text(statement, 1);
    if (!key || !value) {
      continue;
    }
    values[reinterpret_cast<const char*>(key)] = reinterpret_cast<const char*>(value);
  }

  sqlite3_finalize(statement);
  return values;
}

std::map<std::string, std::string> load_variables(const std::filesystem::path& input_path) {
  sqlite3* db = nullptr;
  if (sqlite3_open_v2(input_path.c_str(), &db, SQLITE_OPEN_READONLY, nullptr) != SQLITE_OK) {
    if (db != nullptr) {
      sqlite3_close(db);
    }
    throw std::runtime_error("unable to open sqlite database");
  }

  std::map<std::string, std::string> variables = load_table(db, "system_configuration");
  const std::map<std::string, std::string> summary = load_table(db, "summary");
  sqlite3_close(db);

  const std::string install_prefix = variables["DATACRUMBS_INSTALL_PREFIX"];
  if (!install_prefix.empty()) {
    variables["DATACRUMBS_INSTALL_DIR"] = install_prefix;
  }

  const std::string install_host = variables["DATACRUMBS_INSTALL_HOST"];
  if (!install_host.empty()) {
    variables["DATACRUMBS_HOST"] = install_host;
  }

  if (const auto trace_log_dir = summary.find("trace_log_dir");
      trace_log_dir != summary.end() && !trace_log_dir->second.empty()) {
    variables["DATACRUMBS_CONFIGURED_TRACE_DIR"] = trace_log_dir->second;
  }

  const std::string configured_log_dir = variables["DATACRUMBS_LOG_DIR"];
  if (!configured_log_dir.empty()) {
    variables["DATACRUMBS_CONFIGURED_LOG_DIR"] = configured_log_dir;
  }

  const std::string scheduler = variables["DATACRUMBS_JOB_SCHEDULER"];
  if (!scheduler.empty()) {
    variables["DATACRUMBS_SCHEDULER_TYPE"] = scheduler;
  }

  const std::string job_id_var = variables["DATACRUMBS_JOB_ID_VAR"];
  if (!job_id_var.empty()) {
    variables["DATACRUMBS_SCHEDULER_JOBID_ENV_VAR"] = job_id_var;
  }

  const std::string inclusion_paths = variables["DATACRUMBS_INCLUSION_PATHS"];
  if (!inclusion_paths.empty()) {
    variables["DATACRUMBS_INCLUSION_PATH"] = inclusion_paths;
  }

  if (variables["DATACRUMBS_DISABLE_PROBE_SIGNING"] == "1") {
    variables["DATACRUMBS_DISABLE_PROBE_SIGNING"] = "ON";
  }

  return variables;
}

void write_cmake_file(const std::filesystem::path& output_path,
                      const std::map<std::string, std::string>& variables) {
  std::filesystem::create_directories(output_path.parent_path());
  std::ofstream output(output_path);
  if (!output.is_open()) {
    throw std::runtime_error("unable to open output file");
  }

  output << "# Generated by datacrumbs-system-configuration-loader\n\n";
  for (const auto& [key, value] : variables) {
    output << "set(" << key << " " << cmake_quote(value) << ")\n";
  }
  output << '\n';
}

}  // namespace

int main(int argc, char** argv) {
  try {
    std::string input_path;
    std::string output_path;

    for (int i = 1; i < argc; ++i) {
      const std::string arg = argv[i];
      if (arg == "--input" && i + 1 < argc) {
        input_path = argv[++i];
      } else if (arg == "--output" && i + 1 < argc) {
        output_path = argv[++i];
      } else {
        throw std::runtime_error("usage: --input <path> --output <path>");
      }
    }

    if (input_path.empty() || output_path.empty()) {
      throw std::runtime_error("usage: --input <path> --output <path>");
    }

    const auto variables = load_variables(input_path);
    write_cmake_file(output_path, variables);
    return 0;
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}
