#include <datacrumbs/common/logging.h>
#include <datacrumbs/common/utils.h>
#include <datacrumbs/explorer/probe_explorer.h>

int main(int argc, char** argv) {
  DC_LOG_TRACE("probe_configurator main - start");
  datacrumbs::utils::Timer timer;
  timer.resumeTime();

#ifdef DATACRUMBS_DISABLE_PROBE_SIGNING
  DC_LOG_WARN("Probe signing is disabled. Probes generated by datacrumbs_probe_configurator are not signed.");
#endif

  datacrumbs::ProbeExplorer explorer(argc, argv, true);
  explorer.writeProbesToJson();

  timer.pauseTime();
  DC_LOG_PRINT("Elapsed time in Probe Configurator: %f seconds", timer.getElapsedTime());
  return explorer.has_invalid_probes_ ? 1 : 0;
}
