from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path
from typing import Any


def _cmake_bracket_quote(value: str) -> str:
    return f"[==[{value}]==]"


def _stringify(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "1" if value else "0"
    return str(value)


def _load_payload(path: Path) -> dict[str, Any]:
    with gzip.open(path, "rt", encoding="utf-8") as stream:
        payload = json.load(stream)
    if not isinstance(payload, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return payload


def _system_variables(payload: dict[str, Any]) -> dict[str, str]:
    system_configuration = payload.get("system_configuration") or {}
    summary = payload.get("summary") or {}
    if not isinstance(system_configuration, dict):
        raise ValueError("system_configuration must be a JSON object")
    if not isinstance(summary, dict):
        raise ValueError("summary must be a JSON object when present")

    variables = {
        str(key): _stringify(value)
        for key, value in system_configuration.items()
        if isinstance(key, str)
    }

    install_prefix = variables.get("DATACRUMBS_INSTALL_PREFIX", "")
    if install_prefix:
        variables["DATACRUMBS_INSTALL_PREFIX_PATH"] = install_prefix

    install_host = variables.get("DATACRUMBS_INSTALL_HOST", "")
    if install_host:
        variables["DATACRUMBS_HOST"] = install_host
    elif isinstance(summary.get("config_name"), str):
        variables["DATACRUMBS_HOST"] = summary["config_name"]

    trace_dir = summary.get("trace_log_dir")
    if isinstance(trace_dir, str) and trace_dir:
        variables["DATACRUMBS_CONFIGURED_TRACE_DIR"] = trace_dir

    configured_log_dir = variables.get("DATACRUMBS_LOG_DIR", "")
    if configured_log_dir:
        variables["DATACRUMBS_CONFIGURED_LOG_DIR"] = configured_log_dir

    scheduler = variables.get("DATACRUMBS_JOB_SCHEDULER", "")
    if scheduler:
        variables["DATACRUMBS_SCHEDULER_TYPE"] = scheduler

    job_id_var = variables.get("DATACRUMBS_JOB_ID_VAR", "")
    if job_id_var:
        variables["DATACRUMBS_SCHEDULER_JOBID_ENV_VAR"] = job_id_var

    job_other_flags = variables.get("DATACRUMBS_JOB_OTHER_FLAGS", "")
    if job_other_flags:
        variables["DATACRUMBS_SCHEDULER_RUN_EXTRA_ARGS"] = job_other_flags

    inclusion_paths = variables.get("DATACRUMBS_INCLUSION_PATHS", "")
    if inclusion_paths:
        variables["DATACRUMBS_INCLUSION_PATH"] = inclusion_paths

    if variables.get("DATACRUMBS_DISABLE_PROBE_SIGNING", "") == "1":
        variables["DATACRUMBS_DISABLE_PROBE_SIGNING"] = "ON"

    return variables


def _write_cmake(path: Path, variables: dict[str, str]) -> None:
    lines = ["# Generated by load_datacrumbs_system_configuration.py", ""]
    for key in sorted(variables):
        lines.append(f"set({key} {_cmake_bracket_quote(variables[key])})")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert an installed datacrumbs system-probe json.gz artifact into CMake variables"
    )
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    output_path = Path(args.output).resolve()
    payload = _load_payload(input_path)
    variables = _system_variables(payload)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    _write_cmake(output_path, variables)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
